# Generated by Django 3.2.4 on 2022-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='Cokejnr.png', null=True, upload_to=''),
        ),
    ]
